@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2019.2.1 (64-bit)
=======
REM Vivado (TM) v2019.2 (64-bit)
>>>>>>> a9b88331d7735c42fde1f646bf20ccad7362ae0b
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Sat Oct 16 13:18:14 -0700 2021
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
=======
REM Generated by Vivado on Sat Oct 16 15:34:11 -0700 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
>>>>>>> a9b88331d7735c42fde1f646bf20ccad7362ae0b
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xvlog --incr --relax -prj DataMemory_tb_vlog.prj"
call xvlog  --incr --relax -prj DataMemory_tb_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -prj ALU32Bit_tb_vlog.prj"
call xvlog  --incr --relax -prj ALU32Bit_tb_vlog.prj -log xvlog.log
>>>>>>> a9b88331d7735c42fde1f646bf20ccad7362ae0b
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
