@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2019.2.1 (64-bit)
=======
REM Vivado (TM) v2019.2 (64-bit)
>>>>>>> a9b88331d7735c42fde1f646bf20ccad7362ae0b
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Sat Oct 16 13:18:15 -0700 2021
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
=======
REM Generated by Vivado on Sat Oct 16 15:34:15 -0700 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
>>>>>>> a9b88331d7735c42fde1f646bf20ccad7362ae0b
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xelab -wto 9a12db2147c04af8a24473a968ada1fb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot DataMemory_tb_behav xil_defaultlib.DataMemory_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 9a12db2147c04af8a24473a968ada1fb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot DataMemory_tb_behav xil_defaultlib.DataMemory_tb xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto 9a12db2147c04af8a24473a968ada1fb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ALU32Bit_tb_behav xil_defaultlib.ALU32Bit_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 9a12db2147c04af8a24473a968ada1fb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ALU32Bit_tb_behav xil_defaultlib.ALU32Bit_tb xil_defaultlib.glbl -log elaborate.log
>>>>>>> a9b88331d7735c42fde1f646bf20ccad7362ae0b
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
