@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Dec 04 10:52:44 -0700 2021
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Datapath_tb_behav -key {Behavioral:sim_1:Functional:Datapath_tb} -tclbatch Datapath_tb.tcl -view C:/Users/Nathaniel/Documents/_nrod968/School/ECE-369A/lab9-15/Datapath_tb_behav.wcfg -log simulate.log"
call xsim  Datapath_tb_behav -key {Behavioral:sim_1:Functional:Datapath_tb} -tclbatch Datapath_tb.tcl -view C:/Users/Nathaniel/Documents/_nrod968/School/ECE-369A/lab9-15/Datapath_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
